version: '3'

services:
  db:
    image: postgres:9.6
    volumes:
      - ./octo-spy/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: octo_admin
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  spy:
    image: octo-spy:latest
    environment:
      CATALINA_OPTS: "-Docto-spy.database.host=db"
    ports:
      - 8080:8080
    depends_on:
      - db
  board:
    image: octo-board:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spy
    ports:
      - 8081:80
